# Generated by Django 2.2.13 on 2020-10-07 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(default=1602106945, editable=False)),
                ('modify_at', models.IntegerField(default=1602106945)),
                ('deleted_at', models.IntegerField(null=True)),
                ('average_fuel', models.DecimalField(decimal_places=1, max_digits=3)),
                ('delegation_starting', models.IntegerField()),
                ('delegation_ending', models.IntegerField()),
                ('driver', models.TextField()),
                ('owner', models.TextField()),
                ('type', models.CharField(choices=[('Magán', 'Magán'), ('Céges', 'Céges')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(default=1602106945, editable=False)),
                ('modify_at', models.IntegerField(default=1602106945)),
                ('deleted_at', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=160)),
                ('city', models.TextField()),
                ('address', models.TextField()),
                ('company_name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutoPartnerConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(default=1602106945, editable=False)),
                ('modify_at', models.IntegerField(default=1602106945)),
                ('deleted_at', models.IntegerField(null=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hozzarendelt_partnerek', to='apps.Auto')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hozzarendelt_autok', to='apps.Partner')),
            ],
            options={
                'unique_together': {('auto', 'partner')},
            },
        ),
    ]
