# Generated by Django 2.2.13 on 2020-10-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='created_at',
            field=models.IntegerField(default=1602140598, editable=False),
        ),
        migrations.AlterField(
            model_name='auto',
            name='modify_at',
            field=models.IntegerField(default=1602140598),
        ),
        migrations.AlterField(
            model_name='autopartnerconnection',
            name='created_at',
            field=models.IntegerField(default=1602140598, editable=False),
        ),
        migrations.AlterField(
            model_name='autopartnerconnection',
            name='modify_at',
            field=models.IntegerField(default=1602140598),
        ),
        migrations.AlterField(
            model_name='partner',
            name='created_at',
            field=models.IntegerField(default=1602140598, editable=False),
        ),
        migrations.AlterField(
            model_name='partner',
            name='modify_at',
            field=models.IntegerField(default=1602140598),
        ),
    ]
