# Generated by Django 2.2.13 on 2020-10-08 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20201008_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='autok',
            field=models.ManyToManyField(related_name='hozzarendelt_autok', through='apps.AutoPartnerConnection', to='apps.Auto'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='created_at',
            field=models.IntegerField(default=1602149394, editable=False),
        ),
        migrations.AlterField(
            model_name='auto',
            name='modify_at',
            field=models.IntegerField(default=1602149394),
        ),
        migrations.AlterField(
            model_name='autopartnerconnection',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Auto'),
        ),
        migrations.AlterField(
            model_name='autopartnerconnection',
            name='created_at',
            field=models.IntegerField(default=1602149394, editable=False),
        ),
        migrations.AlterField(
            model_name='autopartnerconnection',
            name='modify_at',
            field=models.IntegerField(default=1602149394),
        ),
        migrations.AlterField(
            model_name='autopartnerconnection',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Partner'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='created_at',
            field=models.IntegerField(default=1602149394, editable=False),
        ),
        migrations.AlterField(
            model_name='partner',
            name='modify_at',
            field=models.IntegerField(default=1602149394),
        ),
    ]
