# Generated by Django 2.2.13 on 2020-10-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20201008_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='autok',
        ),
        migrations.AddField(
            model_name='partner',
            name='hozzarendelt_autok',
            field=models.ManyToManyField(through='apps.AutoPartnerConnection', to='apps.Auto'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='created_at',
            field=models.IntegerField(default=1602149426, editable=False),
        ),
        migrations.AlterField(
            model_name='auto',
            name='modify_at',
            field=models.IntegerField(default=1602149426),
        ),
        migrations.AlterField(
            model_name='autopartnerconnection',
            name='created_at',
            field=models.IntegerField(default=1602149426, editable=False),
        ),
        migrations.AlterField(
            model_name='autopartnerconnection',
            name='modify_at',
            field=models.IntegerField(default=1602149426),
        ),
        migrations.AlterField(
            model_name='partner',
            name='created_at',
            field=models.IntegerField(default=1602149426, editable=False),
        ),
        migrations.AlterField(
            model_name='partner',
            name='modify_at',
            field=models.IntegerField(default=1602149426),
        ),
    ]
