# Generated by Django 2.2.13 on 2020-10-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20201008_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='hozzarendelt_partnerek',
            field=models.ManyToManyField(through='apps.AutoPartnerConnection', to='apps.Partner'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='created_at',
            field=models.IntegerField(default=1602149537, editable=False),
        ),
        migrations.AlterField(
            model_name='auto',
            name='modify_at',
            field=models.IntegerField(default=1602149537),
        ),
        migrations.AlterField(
            model_name='autopartnerconnection',
            name='created_at',
            field=models.IntegerField(default=1602149537, editable=False),
        ),
        migrations.AlterField(
            model_name='autopartnerconnection',
            name='modify_at',
            field=models.IntegerField(default=1602149537),
        ),
        migrations.AlterField(
            model_name='partner',
            name='created_at',
            field=models.IntegerField(default=1602149537, editable=False),
        ),
        migrations.AlterField(
            model_name='partner',
            name='modify_at',
            field=models.IntegerField(default=1602149537),
        ),
    ]
